class Pelicula {
    constructor(titulo, genero, subgenero, director, duracion, clasificacion, imagen, año, puntuacion) {
        this.titulo = titulo;
        this.genero = genero;
        this.subgenero = subgenero;
        this.director = director;
        this.duracion = duracion;
        this.clasificacion = clasificacion;
        this.imagen = imagen  // `https://via.placeholder.com/150x225?text=${encodeURIComponent(titulo)}`;
        this.año = año || 2000;
        this.puntuacion = puntuacion;
    }
}

// Películas 
const peliculas = [
    new Pelicula("Acorralado", "Acción", "Thriller", "Ted Kotcheff", 93, "R", getRutaImagen("Acorralado"), 1982, 7.7),
    new Pelicula("Aladdin", "Fantasía", "Aventura", "Guy Ritchie", 128, "PG", getRutaImagen("Aladdin"), 2019, 6.9),
    new Pelicula("Alien", "Ciencia ficción", "Terror", "Ridley Scott", 117, "R", getRutaImagen("Alien"), 1979, 8.4),
    new Pelicula("Amelie", "Comedia", "Romance", "Jean-Pierre Jeunet", 122, "R", getRutaImagen("Amelie"), 2001, 8.3),
    new Pelicula("American Pie", "Comedia", "Adolescente", "Paul Weitz", 95, "R", getRutaImagen("American Pie"), 1999, 7.0),
    new Pelicula("Amores perros", "Drama", "Thriller", "Alejandro González Iñárritu", 154, "R", getRutaImagen("Amores perros"), 2000, 8.1),
    new Pelicula("Avatar", "Ciencia ficción", "Aventura", "James Cameron", 162, "PG-13", getRutaImagen("Avatar"), 2009, 7.8),
    new Pelicula("Babel", "Drama", "Thriller", "Alejandro González Iñárritu", 143, "R", getRutaImagen("Babel"), 2006, 7.4),
    new Pelicula("Barbie", "Comedia", "Fantasía", "Greta Gerwig", 114, "PG-13", getRutaImagen("Barbie"), 2023, 7.0),
    new Pelicula("Batman: El caballero de la noche", "Acción", "Superhéroes", "Christopher Nolan", 152, "PG-13", getRutaImagen("Batman: El caballero de la noche"), 2008, 9.0),
    new Pelicula("Blade Runner", "Ciencia ficción", "Neo-noir", "Ridley Scott", 117, "R", getRutaImagen("Blade Runner"), 1982, 8.1),
    new Pelicula("Bohemian Rhapsody", "Drama", "Biografía", "Bryan Singer", 134, "PG-13", getRutaImagen("Bohemian Rhapsody"), 2018, 7.9),
    new Pelicula("Buena Vista Social Club", "Documental", "Musical", "Wim Wenders", 105, "G", getRutaImagen("Buena Vista Social Club"), 1999, 7.6),
    new Pelicula("Cadena perpetua", "Drama", "Crimen", "Frank Darabont", 142, "R", getRutaImagen("Cadena perpetua"), 1994, 9.3),
    new Pelicula("Cafarnaúm", "Drama", "Social", "Nadine Labaki", 126, "R", getRutaImagen("Cafarnaúm"), 2018, 8.4),
    new Pelicula("Casablanca", "Drama", "Romance", "Michael Curtiz", 102, "PG", getRutaImagen("Casablanca"), 1942, 8.5),
    new Pelicula("Casino", "Drama", "Crimen", "Martin Scorsese", 178, "R", getRutaImagen("Casino"), 1995, 8.2),
    new Pelicula("Cien años de soledad", "Drama", "Realismo mágico", "Laura Mora", 145, "PG-13", getRutaImagen("Cien años de soledad"), 2024, 7.5),
    new Pelicula("Cinema Paradiso", "Drama", "Romance", "Giuseppe Tornatore", 155, "R", getRutaImagen("Cinema Paradiso"), 1988, 8.5),
    new Pelicula("Ciudad de Dios", "Drama", "Crimen", "Fernando Meirelles", 130, "R", getRutaImagen("Ciudad de Dios"), 2002, 8.6),
    new Pelicula("Coco", "Animación", "Aventura", "Lee Unkrich", 105, "PG", getRutaImagen("Coco"), 2017, 8.4),
    new Pelicula("Crepúsculo", "Fantasía", "Romance", "Catherine Hardwicke", 122, "PG-13", getRutaImagen("Crepúsculo"), 2008, 5.2),
    new Pelicula("Cuando Harry conoció a Sally", "Comedia", "Romance", "Rob Reiner", 96, "R", getRutaImagen("Cuando Harry conoció a Sally"), 1989, 7.7),
    new Pelicula("Cuento de Navidad", "Fantasía", "Drama", "Robert Zemeckis", 96, "PG", getRutaImagen("Cuento de Navidad"), 2009, 6.8),
    new Pelicula("Deadpool", "Acción", "Comedia", "Tim Miller", 108, "R", getRutaImagen("Deadpool"), 2016, 8.0),
    new Pelicula("Django sin cadenas", "Western", "Drama", "Quentin Tarantino", 165, "R", getRutaImagen("Django sin cadenas"), 2012, 8.4),
    new Pelicula("Dune", "Ciencia ficción", "Aventura", "Denis Villeneuve", 155, "PG-13", getRutaImagen("Dune"), 2021, 8.0),
    new Pelicula("E.T., el extraterrestre", "Ciencia ficción", "Aventura", "Steven Spielberg", 115, "PG", getRutaImagen("E.T., el extraterrestre"), 1982, 7.8),
    new Pelicula("El bueno, el feo y el malo", "Western", "Aventura", "Sergio Leone", 178, "R", getRutaImagen("El bueno, el feo y el malo"), 1966, 8.8),
    new Pelicula("El caballero oscuro", "Acción", "Superhéroes", "Christopher Nolan", 152, "PG-13", getRutaImagen("El caballero oscuro"), 2008, 9.0),
    new Pelicula("El club de la lucha", "Drama", "Thriller", "David Fincher", 139, "R", getRutaImagen("El club de la lucha"), 1999, 8.8),
    new Pelicula("El curioso caso de Benjamin Button", "Drama", "Fantasía", "David Fincher", 166, "PG-13", getRutaImagen("El curioso caso de Benjamin Button"), 2008, 7.8),
    new Pelicula("El diablo viste a la moda", "Comedia", "Drama", "David Frankel", 109, "PG-13", getRutaImagen("El diablo viste a la moda"), 2006, 6.9),
    new Pelicula("El exorcista", "Terror", "Sobrenatural", "William Friedkin", 122, "R", getRutaImagen("El exorcista"), 1973, 8.1),
    new Pelicula("El gran hotel Budapest", "Comedia", "Drama", "Wes Anderson", 99, "R", getRutaImagen("El gran hotel Budapest"), 2014, 8.1),
    new Pelicula("El laberinto del fauno", "Fantasía", "Drama", "Guillermo del Toro", 118, "R", getRutaImagen("El laberinto del fauno"), 2006, 8.2),
    new Pelicula("El lobo de Wall Street", "Drama", "Biografía", "Martin Scorsese", 180, "R", getRutaImagen("El lobo de Wall Street"), 2013, 8.2),
    new Pelicula("El mago de Oz", "Fantasía", "Musical", "Victor Fleming", 102, "G", getRutaImagen("El mago de Oz"), 1939, 8.0),
    new Pelicula("El origen", "Ciencia ficción", "Acción", "Christopher Nolan", 148, "PG-13", getRutaImagen("El origen"), 2010, 8.8),
    new Pelicula("El padrino", "Drama", "Crimen", "Francis Ford Coppola", 175, "R", getRutaImagen("El padrino"), 1972, 9.2),
    new Pelicula("El pianista", "Drama", "Biografía", "Roman Polanski", 150, "R", getRutaImagen("El pianista"), 2002, 8.5),
    new Pelicula("El rey león", "Animación", "Aventura", "Roger Allers", 88, "G", getRutaImagen("El rey león"), 1994, 8.5),
    new Pelicula("El secreto de sus ojos", "Drama", "Thriller", "Juan José Campanella", 129, "R", getRutaImagen("El secreto de sus ojos"), 2009, 8.2),
    new Pelicula("El sexto sentido", "Drama", "Terror", "M. Night Shyamalan", 107, "PG-13", getRutaImagen("El sexto sentido"), 1999, 8.1),
    new Pelicula("El silencio de los corderos", "Thriller", "Crimen", "Jonathan Demme", 118, "R", getRutaImagen("El silencio de los corderos"), 1991, 8.6),
    new Pelicula("El último samurái", "Acción", "Drama", "Edward Zwick", 154, "R", getRutaImagen("El último samurái"), 2003, 7.7),
    new Pelicula("En busca de la felicidad", "Drama", "Biografía", "Gabriele Muccino", 117, "PG-13", getRutaImagen("En busca de la felicidad"), 2006, 8.0),
    new Pelicula("Encontrarás dragones", "Drama", "Guerra", "Roland Joffé", 122, "PG-13", getRutaImagen("Encontrarás dragones"), 2011, 5.9),
    new Pelicula("Enemigo a las puertas", "Guerra", "Drama", "Jean-Jacques Annaud", 131, "R", getRutaImagen("Enemigo a las puertas"), 2001, 7.6),
    new Pelicula("Erin Brockovich", "Drama", "Biografía", "Steven Soderbergh", 131, "R", getRutaImagen("Erin Brockovich"), 2000, 7.4),
    new Pelicula("Eterno resplandor de una mente sin recuerdos", "Drama", "Ciencia ficción", "Michel Gondry", 108, "R", getRutaImagen("Eterno resplandor de una mente sin recuerdos"), 2004, 8.3),
    new Pelicula("Forrest Gump", "Drama", "Comedia", "Robert Zemeckis", 142, "PG-13", getRutaImagen("Forrest Gump"), 1994, 8.8),
    new Pelicula("Frida", "Drama", "Biografía", "Julie Taymor", 123, "R", getRutaImagen("Frida"), 2002, 7.4),
    new Pelicula("Frozen", "Animación", "Aventura", "Jennifer Lee", 102, "PG", getRutaImagen("Frozen"), 2013, 7.4),
    new Pelicula("Gladiador", "Acción", "Drama", "Ridley Scott", 155, "R", getRutaImagen("Gladiador"), 2000, 8.5),
    new Pelicula("Gran Torino", "Drama", "Thriller", "Clint Eastwood", 116, "R", getRutaImagen("Gran Torino"), 2008, 8.1),
    new Pelicula("Gravity", "Ciencia ficción", "Thriller", "Alfonso Cuarón", 91, "PG-13", getRutaImagen("Gravity"), 2013, 7.7),
    new Pelicula("Grease", "Musical", "Romance", "Randal Kleiser", 110, "PG", getRutaImagen("Grease"), 1978, 7.2),
    new Pelicula("Harry Potter y la piedra filosofal🦷", "Fantasía", "Aventura", "Chris Columbus", 152, "PG", getRutaImagen("Harry Potter y la piedra filosofal"), 2001, 7.6),
    new Pelicula("Infiltrados", "Thriller", "Crimen", "Martin Scorsese", 151, "R", getRutaImagen("Infiltrados"), 2006, 8.5),
    new Pelicula("Interestelar", "Ciencia ficción", "Aventura", "Christopher Nolan", 169, "PG-13", getRutaImagen("Interestelar"), 2014, 8.6),
    new Pelicula("Intocable", "Drama", "Comedia", "Olivier Nakache", 112, "R", getRutaImagen("Intocable"), 2011, 8.5),
    new Pelicula("Isla de perros", "Animación", "Aventura", "Wes Anderson", 101, "PG-13", getRutaImagen("Isla de perros"), 2018, 7.9),
    new Pelicula("John Wick", "Acción", "Neo-noir", "Chad Stahelski", 101, "R", getRutaImagen("John Wick"), 2014, 7.4),
    new Pelicula("Joker", "Drama", "Thriller", "Todd Phillips", 122, "R", getRutaImagen("Joker"), 2019, 8.4),
    new Pelicula("Jurassic Park", "Ciencia ficción", "Aventura", "Steven Spielberg", 127, "PG-13", getRutaImagen("Jurassic Park"), 1993, 8.2),
    new Pelicula("Kill Bill: Vol. 1", "Acción", "Thriller", "Quentin Tarantino", 111, "R", getRutaImagen("Kill Bill: Vol. 1"), 2003, 8.1),
    new Pelicula("La bella y la bestia", "Fantasía", "Musical", "Bill Condon", 129, "PG", getRutaImagen("La bella y la bestia"), 2017, 7.1),
    new Pelicula("La forma del agua", "Fantasía", "Drama", "Guillermo del Toro", 123, "R", getRutaImagen("La forma del agua"), 2017, 7.3),
    new Pelicula("La historia oficial", "Drama", "Historia", "Luis Puenzo", 112, "R", getRutaImagen("La historia oficial"), 1985, 7.8),
    new Pelicula("La naranja mecánica", "Ciencia ficción", "Drama", "Stanley Kubrick", 136, "R", getRutaImagen("La naranja mecánica"), 1971, 8.3),
    new Pelicula("La noche de los lápices", "Drama", "Historia", "Héctor Olivera", 105, "R", getRutaImagen("La noche de los lápices"), 1986, 7.9),
    new Pelicula("La red social", "Drama", "Biografía", "David Fincher", 120, "PG-13", getRutaImagen("La red social"), 2010, 7.7),
    new Pelicula("La vida es bella", "Drama", "Comedia", "Roberto Benigni", 116, "PG-13", getRutaImagen("La vida es bella"), 1997, 8.6),
    new Pelicula("Las ventajas de ser invisible", "Drama", "Romance", "Stephen Chbosky", 103, "PG-13", getRutaImagen("Las ventajas de ser invisible"), 2012, 8.0),
    new Pelicula("Los juegos del hambre", "Ciencia ficción", "Aventura", "Gary Ross", 142, "PG-13", getRutaImagen("Los juegos del hambre"), 2012, 7.2),
    new Pelicula("Los vengadores", "Acción", "Ciencia ficción", "Joss Whedon", 143, "PG-13", getRutaImagen("Los vengadores"), 2012, 8.0),
    new Pelicula("Mad Max: Furia en el camino", "Acción", "Aventura", "George Miller", 120, "R", getRutaImagen("Mad Max: Furia en el camino"), 2015, 8.1),
    new Pelicula("Mamma Mia!", "Musical", "Comedia", "Phyllida Lloyd", 108, "PG-13", getRutaImagen("Mamma Mia!"), 2008, 6.5),
    new Pelicula("Manchester frente al mar", "Drama", "Tragedia", "Kenneth Lonergan", 137, "R", getRutaImagen("Manchester frente al mar"), 2016, 7.8),
    new Pelicula("Mátalos suavemente", "Crimen", "Thriller", "Andrew Dominik", 97, "R", getRutaImagen("Mátalos suavemente"), 2012, 6.2),
    new Pelicula("Matrix", "Ciencia ficción", "Acción", "The Wachowskis", 136, "R", getRutaImagen("Matrix"), 1999, 8.7),
    new Pelicula("Memento", "Thriller", "Neo-noir", "Christopher Nolan", 113, "R", getRutaImagen("Memento"), 2000, 8.4),
    new Pelicula("Metropolis", "Ciencia ficción", "Drama", "Fritz Lang", 153, "PG", getRutaImagen("Metropolis"), 1927, 8.3),
    new Pelicula("Midnight in Paris", "Comedia", "Romance", "Woody Allen", 94, "PG-13", getRutaImagen("Midnight in Paris"), 2011, 7.7),
    new Pelicula("Mulholland Drive", "Thriller", "Misterio", "David Lynch", 147, "R", getRutaImagen("Mulholland Drive"), 2001, 7.9),
    new Pelicula("Náufrago", "Aventura", "Drama", "Robert Zemeckis", 143, "PG-13", getRutaImagen("Náufrago"), 2000, 7.8),
    new Pelicula("No es país para viejos", "Thriller", "Crimen", "Ethan y Joel Coen", 122, "R", getRutaImagen("No es país para viejos"), 2007, 8.1),
    new Pelicula("Nosferatu", "Terror", "Fantasía", "F.W. Murnau", 94, "PG", getRutaImagen("Nosferatu"), 1922, 7.9),
    new Pelicula("Nueve reinas", "Thriller", "Crimen", "Fabián Bielinsky", 114, "R", getRutaImagen("Nueve reinas"), 2000, 7.9),
    new Pelicula("Nueve semanas y media", "Drama", "Romance", "Adrian Lyne", 117, "R", getRutaImagen("Nueve semanas y media"), 1986, 5.9),
    new Pelicula("Oppenheimer", "Drama", "Biografía", "Christopher Nolan", 180, "R", getRutaImagen("Oppenheimer"), 2023, 8.5),
    new Pelicula("Parasite", "Thriller", "Drama", "Bong Joon-ho", 132, "R", getRutaImagen("Parasite"), 2019, 8.5),
    new Pelicula("Pulp Fiction", "Crimen", "Drama", "Quentin Tarantino", 154, "R", getRutaImagen("Pulp Fiction"), 1994, 8.9),
    new Pelicula("Roma", "Drama", "Historia", "Alfonso Cuarón", 135, "R", getRutaImagen("Roma"), 2018, 7.7),
    new Pelicula("Rushmore", "Comedia", "Drama", "Wes Anderson", 93, "R", getRutaImagen("Rushmore"), 1998, 7.7),
    new Pelicula("Salvar al soldado Ryan", "Guerra", "Drama", "Steven Spielberg", 169, "R", getRutaImagen("Salvar al soldado Ryan"), 1998, 8.6),
    new Pelicula("Seven", "Thriller", "Crimen", "David Fincher", 127, "R", getRutaImagen("Seven"), 1995, 8.6),
    new Pelicula("Shrek", "Animación", "Comedia", "Andrew Adamson", 90, "PG", getRutaImagen("Shrek"), 2001, 7.9),
    new Pelicula("Sin City", "Neo-noir", "Crimen", "Robert Rodriguez", 124, "R", getRutaImagen("Sin City"), 2005, 8.0),
    new Pelicula("Spider-Man: Un nuevo universo", "Animación", "Acción", "Peter Ramsey", 117, "PG", getRutaImagen("Spider-Man: Un nuevo universo"), 2018, 8.4),
    new Pelicula("The Truman Show", "Drama", "Ciencia ficción", "Peter Weir", 103, "PG", getRutaImagen("The Truman Show"), 1998, 8.1),
    new Pelicula("Top Gun: Maverick", "Acción", "Drama", "Joseph Kosinski", 130, "PG-13", getRutaImagen("Top Gun: Maverick"), 2022, 8.3),
    new Pelicula("Toy Story", "Animación", "Aventura", "John Lasseter", 81, "G", getRutaImagen("Toy Story"), 1995, 8.3),
    new Pelicula("Un lugar tranquilo", "Terror", "Ciencia ficción", "John Krasinski", 90, "PG-13", getRutaImagen("Un lugar tranquilo"), 2018, 7.5),
    new Pelicula("Una mente brillante", "Drama", "Biografía", "Ron Howard", 135, "PG-13", getRutaImagen("Una mente brillante"), 2001, 8.2),
    new Pelicula("Volver al futuro", "Ciencia ficción", "Aventura", "Robert Zemeckis", 116, "PG", getRutaImagen("Volver al futuro"), 1985, 8.5),
    new Pelicula("Y tu mamá también", "Drama", "Aventura", "Alfonso Cuarón", 106, "R", getRutaImagen("Y tu mamá también"), 2001, 7.7),
    new Pelicula("Zootopia", "Animación", "Aventura", "Byron Howard", 108, "PG", getRutaImagen("Zootopia"), 2016, 8.0),
    new Pelicula("Harry Potter y la cámara secreta", "Fantasía", "Aventura", "Chris Columbus", 161, "PG", getRutaImagen("Harry Potter y la cámara secreta"), 2002, 7.4),
    new Pelicula("Harry Potter y el prisionero de Azkaban", "Fantasía", "Aventura", "Alfonso Cuarón", 142, "PG", getRutaImagen("Harry Potter y el prisionero de Azkaban"), 2004, 7.9),
    new Pelicula("Harry Potter y el cáliz de fuego", "Fantasía", "Aventura", "Mike Newell", 157, "PG-13", getRutaImagen("Harry Potter y el cáliz de fuego"), 2005, 7.7),
    new Pelicula("Harry Potter y la Orden del Fénix", "Fantasía", "Aventura", "David Yates", 138, "PG-13", getRutaImagen("Harry Potter y la Orden del Fénix"), 2007, 7.5),
    new Pelicula("Harry Potter y el misterio del príncipe", "Fantasía", "Aventura", "David Yates", 153, "PG", getRutaImagen("Harry Potter y el misterio del príncipe"), 2009, 7.6),
    new Pelicula("Harry Potter y las Reliquias de la Muerte: Parte 1", "Fantasía", "Aventura", "David Yates", 146, "PG-13", getRutaImagen("Harry Potter y las Reliquias de la Muerte: Parte 1"), 2010, 7.7),
    new Pelicula("Harry Potter y las Reliquias de la Muerte: Parte 2", "Fantasía", "Aventura", "David Yates", 130, "PG-13", getRutaImagen("Harry Potter y las Reliquias de la Muerte: Parte 2"), 2011, 8.1),
    new Pelicula("Animales fantásticos y dónde encontrarlos", "Fantasía", "Aventura", "David Yates", 133, "PG-13", getRutaImagen("Animales fantásticos y dónde encontrarlos"), 2016, 7.3),
    new Pelicula("Animales fantásticos: Los crímenes de Grindelwald", "Fantasía", "Aventura", "David Yates", 134, "PG-13", getRutaImagen("Animales fantásticos: Los crímenes de Grindelwald"), 2018, 6.6),
    new Pelicula("Animales fantásticos: Los secretos de Dumbledore", "Fantasía", "Aventura", "David Yates", 142, "PG-13", getRutaImagen("Animales fantásticos: Los secretos de Dumbledore"), 2022, 6.2),
    new Pelicula("Iron Man", "Acción", "Superhéroes", "Jon Favreau", 126, "PG-13", getRutaImagen("Iron Man"), 2008, 7.9),
    new Pelicula("El increíble Hulk", "Acción", "Superhéroes", "Louis Leterrier", 112, "PG-13", getRutaImagen("El increíble Hulk"), 2008, 6.7),
    new Pelicula("Iron Man 2", "Acción", "Superhéroes", "Jon Favreau", 124, "PG-13", getRutaImagen("Iron Man 2"), 2010, 7.0),
    new Pelicula("Thor", "Acción", "Superhéroes", "Kenneth Branagh", 115, "PG-13", getRutaImagen("Thor"), 2011, 7.0),
    new Pelicula("Capitán América: El primer vengador", "Acción", "Superhéroes", "Joe Johnston", 124, "PG-13", getRutaImagen("Capitán América: El primer vengador"), 2011, 6.9),
    new Pelicula("Iron Man 3", "Acción", "Superhéroes", "Shane Black", 130, "PG-13", getRutaImagen("Iron Man 3"), 2013, 7.1),
    new Pelicula("Thor: El mundo oscuro", "Acción", "Superhéroes", "Alan Taylor", 112, "PG-13", getRutaImagen("Thor: El mundo oscuro"), 2013, 6.8),
    new Pelicula("Capitán América: El soldado de invierno", "Acción", "Superhéroes", "Anthony y Joe Russo", 136, "PG-13", getRutaImagen("Capitán América: El soldado de invierno"), 2014, 7.7),
    new Pelicula("Guardianes de la Galaxia", "Acción", "Superhéroes", "James Gunn", 121, "PG-13", getRutaImagen("Guardianes de la Galaxia"), 2014, 8.0),
    new Pelicula("Vengadores: La era de Ultrón", "Acción", "Superhéroes", "Joss Whedon", 141, "PG-13", getRutaImagen("Vengadores: La era de Ultrón"), 2015, 7.3),
    new Pelicula("Ant-Man", "Acción", "Superhéroes", "Peyton Reed", 117, "PG-13", getRutaImagen("Ant-Man"), 2015, 7.3),
    new Pelicula("Capitán América: Civil War", "Acción", "Superhéroes", "Anthony y Joe Russo", 147, "PG-13", getRutaImagen("Capitán América: Civil War"), 2016, 7.8),
    new Pelicula("Doctor Strange", "Acción", "Superhéroes", "Scott Derrickson", 115, "PG-13", getRutaImagen("Doctor Strange"), 2016, 7.5),
    new Pelicula("Guardianes de la Galaxia Vol. 2", "Acción", "Superhéroes", "James Gunn", 136, "PG-13", getRutaImagen("Guardianes de la Galaxia Vol. 2"), 2017, 7.6),
    new Pelicula("Spider-Man: Homecoming", "Acción", "Superhéroes", "Jon Watts", 133, "PG-13", getRutaImagen("Spider-Man: Homecoming"), 2017, 7.4),
    new Pelicula("Thor: Ragnarok", "Acción", "Superhéroes", "Taika Waititi", 130, "PG-13", getRutaImagen("Thor: Ragnarok"), 2017, 7.9),
    new Pelicula("Black Panther", "Acción", "Superhéroes", "Ryan Coogler", 134, "PG-13", getRutaImagen("Black Panther"), 2018, 7.3),
    new Pelicula("Vengadores: Infinity War", "Acción", "Superhéroes", "Anthony y Joe Russo", 149, "PG-13", getRutaImagen("Vengadores: Infinity War"), 2018, 8.4),
    new Pelicula("Ant-Man y la Avispa", "Acción", "Superhéroes", "Peyton Reed", 118, "PG-13", getRutaImagen("Ant-Man y la Avispa"), 2018, 7.0),
    new Pelicula("Capitana Marvel", "Acción", "Superhéroes", "Anna Boden y Ryan Fleck", 123, "PG-13", getRutaImagen("Capitana Marvel"), 2019, 6.8),
    new Pelicula("Vengadores: Endgame", "Acción", "Superhéroes", "Anthony y Joe Russo", 181, "PG-13", getRutaImagen("Vengadores: Endgame"), 2019, 8.4),
    new Pelicula("Spider-Man: Lejos de casa", "Acción", "Superhéroes", "Jon Watts", 129, "PG-13", getRutaImagen("Spider-Man: Lejos de casa"), 2019, 7.5),
    new Pelicula("Viuda Negra", "Acción", "Superhéroes", "Cate Shortland", 134, "PG-13", getRutaImagen("Viuda Negra"), 2021, 6.7),
    new Pelicula("Shang-Chi y la leyenda de los Diez Anillos", "Acción", "Superhéroes", "Destin Daniel Cretton", 132, "PG-13", getRutaImagen("Shang-Chi y la leyenda de los Diez Anillos"), 2021, 7.4),
    new Pelicula("Eternals", "Acción", "Superhéroes", "Chloé Zhao", 157, "PG-13", getRutaImagen("Eternals"), 2021, 6.3),
    new Pelicula("Spider-Man: No Way Home", "Acción", "Superhéroes", "Jon Watts", 148, "PG-13", getRutaImagen("Spider-Man: No Way Home"), 2021, 8.2),
    new Pelicula("Doctor Strange en el multiverso de la locura", "Acción", "Superhéroes", "Sam Raimi", 126, "PG-13", getRutaImagen("Doctor Strange en el multiverso de la locura"), 2022, 6.9),
    new Pelicula("Thor: Love and Thunder", "Acción", "Superhéroes", "Taika Waititi", 119, "PG-13", getRutaImagen("Thor: Love and Thunder"), 2022, 6.2),
    new Pelicula("Black Panther: Wakanda Forever", "Acción", "Superhéroes", "Ryan Coogler", 161, "PG-13", getRutaImagen("Black Panther: Wakanda Forever"), 2022, 6.7),
    new Pelicula("Ant-Man y la Avispa: Quantumania", "Acción", "Superhéroes", "Peyton Reed", 125, "PG-13", getRutaImagen("Ant-Man y la Avispa: Quantumania"), 2023, 6.1),
    new Pelicula("Guardianes de la Galaxia Vol. 3", "Acción", "Superhéroes", "James Gunn", 150, "PG-13", getRutaImagen("Guardianes de la Galaxia Vol. 3"), 2023, 7.9),
    new Pelicula("The Marvels", "Acción", "Superhéroes", "Nia DaCosta", 105, "PG-13", getRutaImagen("The Marvels"), 2023, 5.9),
    new Pelicula("Deadpool & Wolverine", "Acción", "Superhéroes", "Shawn Levy", 127, "R", getRutaImagen("Deadpool & Wolverine"), 2024, 7.8),
    new Pelicula("Captain America: Brave New World", "Acción", "Superhéroes", "Julius Onah", 130, "PG-13", getRutaImagen("Captain America: Brave New World"), 2025, 0)
];

// Subgéneros por género 
const subgeneros = {
    "Acción": ["Thriller", "Superhéroes", "Comedia", "Drama", "Neo-noir", "Ciencia ficción", "Aventura"],
    "Animación": ["Aventura", "Comedia", "Acción"],
    "Aventura": ["Drama"],
    "Ciencia ficción": ["Aventura", "Terror", "Neo-noir", "Acción", "Thriller", "Drama"],
    "Comedia": ["Romance", "Adolescente", "Fantasía", "Drama"],
    "Crimen": ["Thriller", "Drama"],
    "Documental": ["Musical"],
    "Drama": ["Aventura", "Ciencia ficción", "Social", "Realismo mágico", "Biografía", "Fantasía", "Historia", "Romance", "Tragedia", "Comedia", "Thriller", "Guerra", "Terror", "Crimen"],
    "Fantasía": ["Drama", "Musical", "Aventura", "Romance"],
    "Guerra": ["Drama"],
    "Musical": ["Comedia", "Romance"],
    "Neo-noir": ["Crimen"],
    "Terror": ["Ciencia ficción", "Fantasía", "Sobrenatural"],
    "Thriller": ["Crimen", "Drama", "Misterio", "Neo-noir"],
    "Western": ["Aventura", "Drama"]
};

// Directores por género 
/* const directores = {
    "Acción": ["Ted Kotcheff", "Jon Watts", "Taika Waititi", "Peyton Reed", "Alan Taylor", "Anthony y Joe Russo", "Kenneth Branagh", "Christopher Nolan", "Tim Miller", "Edward Zwick", "Ridley Scott", "Joseph Kosinski", "Chad Stahelski", "Joss Whedon", "George Miller", "Jon Favreau", "Joe Johnston", "Louis Leterrier", "Shane Black", "James Gunn", "Scott Derrickson", "Ryan Coogler", "Peyton Reed", "Anna Boden y Ryan Fleck", "Cate Shortland", "Destin Daniel Cretton", "Chloé Zhao", "Sam Raimi", "Nia DaCosta", "Shawn Levy", "Julius Onah"],
    "Animación": ["Lee Unkrich", "Roger Allers", "Jennifer Lee", "Peter Ramsey", "John Lasseter", "Wes Anderson", "Andrew Adamson", "Byron Howard"],
    "Aventura": ["Robert Zemeckis"],
    "Ciencia ficción": ["Ridley Scott", "James Cameron", "Denis Villeneuve", "Steven Spielberg", "Alfonso Cuarón", "Christopher Nolan", "Stanley Kubrick", "Gary Ross", "The Wachowskis", "Fritz Lang", "Robert Zemeckis"],
    "Comedia": ["Jean-Pierre Jeunet", "Paul Weitz", "Greta Gerwig", "Rob Reiner", "David Frankel", "Wes Anderson", "Woody Allen"],
    "Crimen": ["Andrew Dominik", "Quentin Tarantino"],
    "Documental": ["Wim Wenders"],
    "Drama": ["Alejandro González Iñárritu", "Stephen Chbosky", "Roberto Benigni", "Roland Joffé", "Steven Soderbergh", "Gabriele Muccino", "M. Night Shyamalan", "Juan José Campanella", "Roman Polanski", "Bryan Singer", "Héctor Olivera", "Frank Darabont", "Nadine Labaki", "Michael Curtiz", "Martin Scorsese", "Laura Mora", "Giuseppe Tornatore", "Michel Gondry", "Robert Zemeckis", "Todd Phillips", "Clint Eastwood", "Olivier Nakache", "Julie Taymor", "Adrian Lyne", "Francis Ford Coppola", "Luis Puenzo", "Christopher Nolan", "Ron Howard", "Alfonso Cuarón", "Fernando Meirelles", "Peter Weir", "Kenneth Lonergan", "David Fincher"],
    "Fantasía": ["Catherine Hardwicke", "Robert Zemeckis", "Guillermo del Toro", "Victor Fleming", "Chris Columbus", "Bill Condon", "Alfonso Cuarón", "Mike Newell", "David Yates"],
    "Guerra": ["Guy Ritchie", "Jean-Jacques Annaud", "Steven Spielberg"],
    "Musical": ["Randal Kleiser", "Phyllida Lloyd"],
    "Neo-noir": ["Robert Rodriguez"],
    "Terror": ["William Friedkin", "F.W. Murnau", "John Krasinski"],
    "Thriller": ["Jonathan Demme", "Martin Scorsese", "Christopher Nolan", "David Lynch", "Ethan y Joel Coen", "Bong Joon-ho", "David Fincher"],
    "Western": ["Quentin Tarantino", "Sergio Leone", "Fabián Bielinsky"]
}; */

const generos_BD = [...(new Set(peliculas.map((pelicula)=>{return pelicula.genero})))]; //obtengo los generos de todas las pelis
let directores = {}; //para ir almacenando los pares genero:[directores]
for(let i =0; i<generos_BD.length;i++){ //itera sobre cada genero, luego busca en cada peli si hay coincidencia de genero o subgenero, si es así luego guarda el director de la peli en una lista y al final agrega el par 
    gen = generos_BD[i];
    coincidencias = peliculas.filter((peli) => ((peli.genero == gen)));
    let coinc_direct = [...(new Set(coincidencias.map((peli)=>{return peli.director})))];
    directores[gen] = coinc_direct;
}

function getRutaImagen(titulo) {
    const nombreArchivo = titulo.replace(/:/g, '');
    return `./imagenes/${nombreArchivo.toLowerCase()}.jpg`;
  }